<div class="bk-modal-wrap" x-data="buckaroo.modal()" x-init="initModal()">
    <div
            id="bk-modal"
            tabindex="-1"
            x-ref="modal"
            aria-hidden="!showModal"
            inert="!showModal"
            x-cloak
            class="fixed top-0 left-0 right-0 z-50 justify-center w-full p-4 items-center overflow-x-hidden overflow-y-auto md:inset-0 max-h-full h-full"
            x-bind:class="showModal ? 'flex' : 'hidden'"
            @keydown.window.escape="close()"
    >
        <div class="relative w-full max-w-md max-h-full" @click.outside="close()">
            <!-- Modal content -->
            <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
                <!-- Modal header -->
                <div class="flex items-start justify-between p-4 border-b rounded-t dark:border-gray-600">
                    <h3 class="text-xl font-semibold text-gray-900 dark:text-white" x-text="title">
                    </h3>
                    <button
                        type="button"
                        @click="close()"
                        class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-600 dark:hover:text-white"
                        data-modal-hide="defaultModal"
                    >
                        <svg
                            aria-hidden="true"
                            class="w-5 h-5"
                            fill="currentColor"
                            viewBox="0 0 20 20"
                            xmlns="http://www.w3.org/2000/svg"
                        >
                            <path
                                fill-rule="evenodd"
                                d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                                clip-rule="evenodd">
                            </path>
                        </svg>
                        <span class="sr-only">Close modal</span>
                    </button>
                </div>
                <!-- Modal body -->
                <div class="p-6 space-y-6">
                    <p class="text-base leading-relaxed text-gray-500 dark:text-gray-400" x-html="content">
                    </p>
                </div>
                <!-- Modal footer -->
                <div class="flex items-center p-2 space-x-2 border-t border-gray-200 rounded-b dark:border-gray-600">
                    <template x-if="Array.isArray(buttons)">
                        <template x-for="(button, index) in buttons" :key="index">
                            <button
                                @click="typeof button.action === 'function' ? button.action() : close()"
                                type="button"
                                class="btn btn primary"
                                x-text="button.label"
                            ></button>
                        </template>
                    </template>
                    <template x-if="showClose">
                        <button @click="close()" type="button" class="btn btn primary">
                            <?= $escaper->escapeHtml(__('Close')); ?>
                        </button>
                    </template>
                </div>
            </div>
        </div>
    </div>
</div>
