<script>
    let buckarooTask;
    window.addEventListener("buckaroo-add-task", (event) => {
        console.log(event);
        if(event.detail.buckarooTask) {
            buckarooTask = event.detail.buckarooTask;
        }
    });

    document.addEventListener("DOMContentLoaded", () => {
        hyvaCheckout.navigation.addTask( async () => {
            if(buckarooTask) {
                await buckarooTask();
            }
        })
        
        function buckaroo_load_sdk() {
            return new Promise(resolve => {
                const script = document.createElement('script');
                script.type = 'text/javascript';
                script.src = '//static.buckaroo.nl/script/ClientSideEncryption001.js';
                script.async = true;
                script.onload = resolve;
                document.head.appendChild(script);
            })
        }

        buckaroo_load_sdk().then(() => {

            hyva.formValidation.addRule('bk-validateCardNumber', (value) => {
                if (!BuckarooClientSideEncryption.V001.validateCardNumber(value.replace(/\s+/g, ''))) {
                    return '<?= $escaper->escapeJs(__('Please enter a valid creditcard number.')) ?>';
                };
                return true;
            });

            hyva.formValidation.addRule('bk-validateCardHolderName', (value) => {
                if (!BuckarooClientSideEncryption.V001.validateCardholderName(value)) {
                    return '<?= $escaper->escapeJs(__('Please enter a valid card holder name.')) ?>';
                };
                return true;
            });

            hyva.formValidation.addRule('bk-ValidateYear', (value) => {
                const message = '<?= $escaper->escapeJs(__('Enter a valid year number.')) ?>';

                if (value.length === 0) {
                    return message;
                }
                const parts = value.split("/");
                if (!BuckarooClientSideEncryption.V001.validateYear(parts[1])) {
                    return message;
                };
                return true;
            });

            hyva.formValidation.addRule('bk-ValidateMonth', (value) => {
                const message = '<?= $escaper->escapeJs(__('Enter a valid month number.')) ?>';
                if (value.length === 0) {
                    return message;
                }

                const parts = value.split("/");
                if (!BuckarooClientSideEncryption.V001.validateMonth(parts[0])) {
                    return message;
                };
                return true;
            });
            window.dispatchEvent(new CustomEvent("buckaroo-cse-load"));
        })


        Magewire.hook('element.removed', (el, component) => {
            if (el.id !== undefined && el.id.indexOf('payment-method-view-buckaroo_magento2') > -1) {
                buckarooTask = undefined;
            }
        })
    });
</script>