<script>
    let buckarooTask;
    window.addEventListener("buckaroo-add-task", (event) => {
        if (event.detail.buckarooTask) {
            buckarooTask = event.detail.buckarooTask;
        }
    });

    document.addEventListener("DOMContentLoaded", () => {
        hyvaCheckout.navigation.addTask(async () => {
            if (buckarooTask) {
                await buckarooTask();
            }
        })

        function buckaroo_load_sdk() {
            return new Promise(resolve => {
                const script = document.createElement('script');
                script.type = 'text/javascript';
                script.src = '//static.buckaroo.nl/script/ClientSideEncryption001.js';
                script.async = true;
                script.onload = resolve;
                document.head.appendChild(script);
            })
        }

        buckaroo_load_sdk().then(() => {

            hyva.formValidation.addRule('bk-validateCardNumber', (value) => {
                if (!BuckarooClientSideEncryption.V001.validateCardNumber(value.replace(/\s+/g, ''))) {
                    return '<?= $escaper->escapeJs(__('Please enter a valid creditcard number.')) ?>';
                };
                return true;
            });

            hyva.formValidation.addRule('bk-validateCardCvc', (value, options, field, context) => {
                if (!BuckarooClientSideEncryption.V001.validateCvc(value, context.determineIssuer(context.cardNumber))) {
                    return '<?= $escaper->escapeJs(__('Please enter a valid Cvc number.')) ?>';
                };
                return true;
            });

            hyva.formValidation.addRule('bk-validateCardHolderName', (value) => {
                if (!BuckarooClientSideEncryption.V001.validateCardholderName(value)) {
                    return '<?= $escaper->escapeJs(__('Please enter a valid card holder name.')) ?>';
                };
                return true;
            });

            hyva.formValidation.addRule('bk-ValidateYear', (value) => {
                const message = '<?= $escaper->escapeJs(__('Enter a valid year number.')) ?>';

                if (value.length === 0) {
                    return message;
                }
                const parts = value.split("/");
                if (!BuckarooClientSideEncryption.V001.validateYear(parts[1])) {
                    return message;
                };
                return true;
            });

            hyva.formValidation.addRule('bk-ValidateMonth', (value) => {
                const message = '<?= $escaper->escapeJs(__('Enter a valid month number.')) ?>';
                if (value.length === 0) {
                    return message;
                }

                const parts = value.split("/");
                if (!BuckarooClientSideEncryption.V001.validateMonth(parts[0])) {
                    return message;
                };
                return true;
            });
            window.dispatchEvent(new CustomEvent("buckaroo-cse-load"));
        })


        Magewire.hook('element.removed', (el, component) => {
            if (el.id !== undefined && el.id.indexOf('payment-method-view-buckaroo_magento2') > -1) {
                buckarooTask = undefined;
            }
        })
    });
</script>
<div class="bk-modal-wrap" x-data="{
    showModal: false,
    title: '<?= $escaper->escapeHtml(__('Success')); ?>',
    content: '',
    showClose: true,
    buttons:[],
    close() {
        this.showModal = false;
    },
    initModal() {
        window.addEventListener('buckaroo-modal-show', (event) => {
            console.log(event);
            if(event.detail.data) {
                this.showModal = true;
                Object.keys(event.detail.data).forEach((key) => {
                    this[key] = event.detail.data[key];
                })
            }
        })

        window.addEventListener('buckaroo-modal-hide', () => {
            this.close();
        })
    }
}" x-init="initModal()">
    <div id="bk-modal" tabindex="-1" aria-hidden="true" class="fixed top-0 left-0 right-0 z-50 justify-center w-full p-4 items-center overflow-x-hidden overflow-y-auto md:inset-0 max-h-full h-full" x-bind:class="showModal ? 'flex': 'hidden'">
        <div class="relative w-full max-w-md max-h-full"  @click.outside="close()">
            <!-- Modal content -->
            <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
                <!-- Modal header -->
                <div class="flex items-start justify-between p-4 border-b rounded-t dark:border-gray-600">
                    <h3 class="text-xl font-semibold text-gray-900 dark:text-white" x-text="title">
                    </h3>
                    <button type="button" @click="close()" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-hide="defaultModal">
                        <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                        </svg>
                        <span class="sr-only">Close modal</span>
                    </button>
                </div>
                <!-- Modal body -->
                <div class="p-6 space-y-6">
                    <p class="text-base leading-relaxed text-gray-500 dark:text-gray-400" x-html="content">
                    </p>
                </div>
                <!-- Modal footer -->
                
                <div class="flex items-center p-2 space-x-2 border-t border-gray-200 rounded-b dark:border-gray-600">
                    <template x-if="Array.isArray(buttons)">
                        <template x-for="(button, index) in buttons" :key="index">
                            <button @click="typeof button.action === 'function' ? button.action() : close()" type="button" class="btn btn primary" x-text="button.label"></button>
                        </template>
                    </template>
                    <template x-if="showClose">
                        <button @click="close()" type="button" class="btn btn primary"><?= $escaper->escapeHtml(__('Close')); ?></button>
                    </template>
                </div>
            </div>
        </div>
    </div>
</div>