<?php

declare(strict_types=1);
/** @var Escaper $escaper */
/** @var \Buckaroo\HyvaCheckout\Magewire\Checkout\Payment\Method\AfterpayBase $magewire */

use Magento\Framework\Escaper;
?>
<div class="col-span-6">
    <div class="flex flex-col gap-y-2 field field-reserved">
        <label for="buckaroo_afterpay_tos_fullname">
            <?= $escaper->escapeHtml(__('Billing Name:')); ?>
        </label>
        <input type="text" wire:model.lazy="fullName" disabled id="buckaroo_afterpay_tos_fullname" class="bg-gray-200">
    </div>

    <?php if ($magewire->showBirth()) {
    ?>
        <div class="flex flex-col gap-y-2 field field-reserved">
            <label for="buckaroo_afterpay_dob">
                <?= $escaper->escapeHtml(__('Date of Birth:')); ?>
                <span class="text-red-600">*</span>
            </label>
            <input
                type="date"
                x-data="buckarooDateHandler"
                x-bind:value="value"
                @blur="handleDateChange"
                data-initial-value="<?= $escaper->escapeHtmlAttr($magewire->dateOfBirth ?? '') ?>"
                id="buckaroo_afterpay_dob"
            >
            <?php if ($magewire->hasError('dateOfBirth')) : ?>
                <div class="text-red-600"><?= $escaper->escapeHtmlAttr($magewire->getError('dateOfBirth')) ?></div>
            <?php endif; ?>
        </div>
    <?php
    } ?>

    <?php if ($magewire->showPhone()) {
    ?>
        <div class="flex flex-col gap-y-2 field field-reserved">
            <label for="buckaroo_afterpay_phone">
                <?= $escaper->escapeHtml(__('Telephone:')); ?>
                <span class="text-red-600">*</span>
            </label>
            <input type="text" wire:model.lazy="phone" id="buckaroo_afterpay_phone">
            <?php if ($magewire->hasError('phone')) : ?>
                <div class="text-red-600"><?= $escaper->escapeHtmlAttr($magewire->getError('phone')) ?></div>
            <?php endif; ?>
        </div>
    <?php
    } ?>

    <?php if ($magewire->showBusinessSelector()) {
    ?>
        <div class="flex flex-col gap-y-2 field field-reserved">
            <label for="buckaroo_magento2_afterpay_selectedBusiness">
                <?= $escaper->escapeHtml(__('Business Model:')); ?>
            </label>
            <select
                name="issuer"
                id="buckaroo_magento2_afterpay_selectedBusiness"
                wire:model="selectedBusiness"
                class="form-select"
            >
                <option value="1"><?= $escaper->escapeHtml(__('B2C - Business to Consumer')) ?></option>
                <option value="2"><?= $escaper->escapeHtml(__('B2B - Business to Business')) ?></option>
            </select>
        </div>
    <?php
    } ?>
    <?php if ($magewire->showIban()) {
    ?>
        <div class="flex flex-col gap-y-2 field field-reserved">
            <label for="buckaroo_afterpay_iban">
                <?= $escaper->escapeHtml(__('Bank Account Number:')); ?>
                <span class="text-red-600">*</span>
            </label>
            <input type="text" wire:model.lazy="iban" id="buckaroo_afterpay_iban">
            <?php if ($magewire->hasError('iban')) : ?>
                <div class="text-red-600"><?= $escaper->escapeHtmlAttr($magewire->getError('iban')) ?></div>
            <?php endif; ?>
        </div>
    <?php
    } ?>
    <?php if ($magewire->showB2b()) {
    ?>
        <div class="flex flex-col gap-y-2 field field-reserved">
            <label for="buckaroo_afterpay_coc">
                <?= $escaper->escapeHtml(__('COC Number:')); ?>
                <span class="text-red-600">*</span>
            </label>
            <input type="text" wire:model.lazy="coc" id="buckaroo_afterpay_coc">
            <?php if ($magewire->hasError('coc')) : ?>
                <div class="text-red-600"><?= $escaper->escapeHtmlAttr($magewire->getError('coc')) ?></div>
            <?php endif; ?>
        </div>

        <div class="flex flex-col gap-y-2 field field-reserved">
            <label for="buckaroo_afterpay_company_name">
                <?= $escaper->escapeHtml(__('Company Name:')); ?>
                <span class="text-red-600">*</span>
            </label>
            <input type="text" wire:model.lazy="companyName" id="buckaroo_afterpay_company_name">
            <?php if ($magewire->hasError('companyName')) : ?>
                <div class="text-red-600"><?= $escaper->escapeHtmlAttr($magewire->getError('companyName')) ?></div>
            <?php endif; ?>
        </div>
    <?php
    } ?>

    <div class="flex flex-col gap-y-2 ">
        <label for="buckaroo_afterpay_tos"><?= $escaper->escapeHtml(__('Terms and Conditions:')); ?></label>
        <div class="flex flex-row gap-x-2">
            <input class="mt-1" type="checkbox" wire:model.lazy="tos" id="buckaroo_afterpay_tos">
            <a target="_blank" class="grow" href="<?= $escaper->escapeUrl($magewire->getTosLink()) ?>">
                <?= $escaper->escapeHtml(
                    __('The general Terms and Conditions for the Riverty payment method apply. The privacy policy of Riverty can be found here.')
                ) ?>
            </a>
        </div>
        <?php if ($magewire->hasError('tos')) : ?>
            <div class="text-red-600"><?= $escaper->escapeHtmlAttr($magewire->getError('tos')) ?></div>
        <?php endif; ?>
    </div>
</div>
