<?php

declare(strict_types=1);
/** @var Escaper $escaper */
/** @var \Buckaroo\HyvaCheckout\Magewire\Checkout\Payment\Method\Afterpay20 $magewire */

use Magento\Framework\Escaper;
?>
<div class="col-span-6">
    <div class="flex flex-col gap-y-2 field field-reserved">
        <label for="buckaroo_afterpay20_tos_fullname">
            <?= $escaper->escapeHtml(__('Billing Name:')); ?>
        </label>
        <input type="text" wire:model.lazy="fullName" disabled id="buckaroo_afterpay20_tos_fullname" class="bg-gray-200">
    </div>

    <?php if ($magewire->showBirth()) {
    ?>
        <div class="flex flex-col gap-y-2 field field-reserved">
            <label for="buckaroo_afterpay20_dob">
                <?= $escaper->escapeHtml(__('Date of Birth:')); ?>
                <span class="text-red">*</span>
            </label>
            <input type="date" x-data value="<?=$magewire->dateOfBirth ?>" @blur="$wire.call('updatedDateOfBirth', $event.target.value); console.log($event.target.value)" id="buckaroo_afterpay20_dob">
            <?php if ($magewire->hasError('dateOfBirth')): ?>
               <div class="text-red"><?= $escaper->escapeHtmlAttr($magewire->getError('dateOfBirth')) ?></div>
            <?php endif; ?>
        </div>
    <?php
    } ?>

    <?php if ($magewire->showIdentificationNumber()) {
    ?>
        <div class="flex flex-col gap-y-2 field field-reserved">
            <label for="buckaroo_afterpay20_identification">
                <?= $escaper->escapeHtml(__('Identification number:')); ?>
                <span class="text-red">*</span>
            </label>
            <input type="text" wire:model.lazy="identificationNumber" id="buckaroo_afterpay20_identification">
            <?php if ($magewire->hasError('identificationNumber')): ?>
               <div class="text-red"><?= $escaper->escapeHtmlAttr($magewire->getError('identificationNumber')) ?></div>
            <?php endif; ?>
        </div>
    <?php
    } ?>

<?php if ($magewire->showPhone()) {
    ?>
        <div class="flex flex-col gap-y-2 field field-reserved">
            <label for="buckaroo_afterpay20_phone">
                <?= $escaper->escapeHtml(__('Telephone:')); ?>
                <span class="text-red">*</span>
            </label>
            <input type="text" wire:model.lazy="phone" id="buckaroo_afterpay20_phone">
            <?php if ($magewire->hasError('phone')): ?>
               <div class="text-red"><?= $escaper->escapeHtmlAttr($magewire->getError('phone')) ?></div>
            <?php endif; ?>
        </div>
    <?php
    } ?>
    
    <?php if ($magewire->showCOC()) {
    ?>
        <div class="flex flex-col gap-y-2 field field-reserved">
            <label for="buckaroo_afterpay20_coc">
                <?= $escaper->escapeHtml(__('COC Number:')); ?>
                <span class="text-red">*</span>
            </label>
            <input type="text" wire:model.lazy="coc" id="buckaroo_afterpay20_coc">
            <?php if ($magewire->hasError('coc')): ?>
               <div class="text-red"><?= $escaper->escapeHtmlAttr($magewire->getError('coc')) ?></div>
            <?php endif; ?>
        </div>
    <?php
    } ?>

    

    <div class="flex flex-col gap-y-2 ">
        <label for="buckaroo_afterpay20_tos"><?= $escaper->escapeHtml(__('Terms and Conditions:')); ?></label>
        <div class="flex flex-row gap-x-2">
            <input class="mt-1" type="checkbox" wire:model.lazy="tos" id="buckaroo_afterpay20_tos">
            <a class="grow" href="<?= $escaper->escapeUrl($magewire->getTosLink()) ?>"><?= $escaper->escapeHtml(__('Yes, I accept the terms and condition for the use of Riverty | Afterpay.')) ?></a>
        </div>
        <?php if ($magewire->hasError('tos')): ?>
            <div class="text-red"><?= $escaper->escapeHtmlAttr($magewire->getError('tos')) ?></div>
        <?php endif; ?>
    </div>
</div>
