<?php

declare(strict_types=1);
/** @var Escaper $escaper */
/** @var \Buckaroo\HyvaCheckout\Magewire\Checkout\Payment\Method\Afterpay20 $magewire */

use Magento\Framework\Escaper;
?>
<div class="col-span-6">
    <div class="flex flex-col gap-y-2 field field-reserved">
        <label for="buckaroo_afterpay20_tos_fullname">
            <?= $escaper->escapeHtml(__('Billing Name:')); ?>
        </label>
        <input
            type="text"
            wire:model.lazy="fullName"
            disabled id="buckaroo_afterpay20_tos_fullname"
            class="bg-gray-200"
        >
    </div>

    <?php if ($magewire->showBirth()) {
    ?>
        <div class="flex flex-col gap-y-2 field field-reserved">
            <label for="buckaroo_afterpay20_dob">
                <?= $escaper->escapeHtml(__('Date of Birth:')); ?>
                <span class="text-red-600">*</span>
            </label>
            <input type="date"
                x-data="buckarooDateHandler"
                x-bind:value="value"
                @blur="handleDateChange"
                data-initial-value="<?= $escaper->escapeHtmlAttr($magewire->dateOfBirth ?? '') ?>"
                id="buckaroo_afterpay20_dob"
            >
            <?php if ($magewire->hasError('dateOfBirth')): ?>
               <div class="text-red-600"><?= $escaper->escapeHtmlAttr($magewire->getError('dateOfBirth')) ?></div>
            <?php endif; ?>
        </div>
    <?php
    } ?>

    <?php if ($magewire->showIdentificationNumber()) {
    ?>
        <div class="flex flex-col gap-y-2 field field-reserved">
            <label for="buckaroo_afterpay20_identification">
                <?= $escaper->escapeHtml(__('Identification number:')); ?>
                <span class="text-red-600">*</span>
            </label>
            <input type="text" wire:model.lazy="identificationNumber" id="buckaroo_afterpay20_identification">
            <?php if ($magewire->hasError('identificationNumber')): ?>
               <div class="text-red-600"><?= $escaper->escapeHtmlAttr($magewire->getError('identificationNumber')) ?></div>
            <?php endif; ?>
        </div>
    <?php
    } ?>

<?php if ($magewire->showPhone()) {
    ?>
        <div class="flex flex-col gap-y-2 field field-reserved">
            <label for="buckaroo_afterpay20_phone">
                <?= $escaper->escapeHtml(__('Telephone:')); ?>
                <span class="text-red-600">*</span>
            </label>
            <input type="text" wire:model.lazy="phone" id="buckaroo_afterpay20_phone">
            <?php if ($magewire->hasError('phone')): ?>
               <div class="text-red-600"><?= $escaper->escapeHtmlAttr($magewire->getError('phone')) ?></div>
            <?php endif; ?>
        </div>
    <?php
    } ?>

    <?php if ($magewire->showCOC()) {
    ?>
        <div class="flex flex-col gap-y-2 field field-reserved">
            <label for="buckaroo_afterpay20_coc">
                <?= $escaper->escapeHtml(__('COC Number:')); ?>
                <span class="text-red-600">*</span>
            </label>
            <input type="text" wire:model.lazy="coc" id="buckaroo_afterpay20_coc">
            <?php if ($magewire->hasError('coc')): ?>
               <div class="text-red-600"><?= $escaper->escapeHtmlAttr($magewire->getError('coc')) ?></div>
            <?php endif; ?>
        </div>
    <?php
    } ?>



    <div class="flex flex-col gap-y-2 ">
        <label for="buckaroo_afterpay20_tos"><?= $escaper->escapeHtml(__('Terms and Conditions:')); ?></label>
        <div class="flex flex-row gap-x-2">
            <input class="mt-1" type="checkbox" wire:model.lazy="tos" id="buckaroo_afterpay20_tos">
            <a class="grow" href="<?= $escaper->escapeUrl($magewire->getTosLink()) ?>">
                <?= $escaper->escapeHtml(
                    __('The general Terms and Conditions for the Riverty payment method apply. The privacy policy of Riverty can be found here.')
                ) ?>
            </a>
        </div>
        <?php if ($magewire->hasError('tos')): ?>
            <div class="text-red-600"><?= $escaper->escapeHtmlAttr($magewire->getError('tos')) ?></div>
        <?php endif; ?>
    </div>

    <?php if ($magewire->showFinancialWarning()): ?>
        <div class="mt-4 p-4 bg-yellow-50 border border-yellow-200 rounded-lg">
            <div class="flex">
                <div class="ml-3">
                    <p class="text-sm text-yellow-800">
                        <?= $escaper->escapeHtml(__('Je moet minimaal 18+ zijn om deze dienst te gebruiken. Als je op tijd betaalt, voorkom je extra kosten en zorg je dat je in de toekomst nogmaals gebruik kunt maken van de diensten van Achteraf betalen via Riverty. Door verder te gaan, accepteer je de Algemene Voorwaarden en bevestig je dat je de Privacyverklaring en Cookieverklaring hebt gelezen.')) ?>
                    </p>
                </div>
            </div>
        </div>
    <?php endif; ?>
</div>
