<?php
/** @var \Buckaroo\HyvaCheckout\Magewire\Payment\Method\Applepay $magewire */
/** @var Magento\Framework\Escaper $escaper */

$isClientSide = (bool) $magewire->getIntegrationMode();
?>
<div class="col-span-6">
    <form 
        x-data="buckarooApplepay" 
        data-is-client-side="<?= $isClientSide ? 'true' : 'false' ?>"
        data-js-sdk-url="<?= $escaper->escapeHtmlAttr($magewire->getJsSdkUrl()) ?>"
        novalidate
    >
    </form>
</div>
