<?php

declare(strict_types=1);
/** @var Escaper $escaper */
/** @var \Buckaroo\HyvaCheckout\Magewire\Payment\Method\Billink $magewire */

use Magento\Framework\Escaper;
?>
<div class="col-span-6">
    <?php if ($magewire->showPhone()) {
        ?>
        <div class="flex flex-col gap-y-2 field field-reserved">
            <label for="buckaroo_billink_phone">
                <?= $escaper->escapeHtml(__('Telephone:')); ?>
                <span class="text-red-600">*</span>
            </label>
            <input type="text" wire:model.lazy="phone" id="buckaroo_billink_phone">
            <?php if ($magewire->hasError('phone')) : ?>
                <div class="text-red-600"><?= $escaper->escapeHtmlAttr($magewire->getError('phone')) ?></div>
            <?php endif; ?>
        </div>
        <?php
    } ?>

    <?php if ($magewire->showB2b()) {
        ?>
        <div class="flex flex-col gap-y-2 field field-reserved">
            <label for="buckaroo_billink_coc">
                <?= $escaper->escapeHtml(__('COC Number:')); ?>
                <span class="text-red-600">*</span>
            </label>
            <input type="text" wire:model.lazy="coc" id="buckaroo_billink_coc">
            <?php if ($magewire->hasError('coc')) : ?>
                <div class="text-red-600"><?= $escaper->escapeHtmlAttr($magewire->getError('coc')) ?></div>
            <?php endif; ?>
        </div>

        <div class="flex flex-col gap-y-2 field field-reserved">
            <label for="buckaroo_billink_vat_number">
                <?= $escaper->escapeHtml(__('Bank Account Number:')); ?>
            </label>
            <input type="text" wire:model.lazy="vatNumber" id="buckaroo_billink_vat_number">
            <?php if ($magewire->hasError('vatNumber')) : ?>
                <div class="text-red-600"><?= $escaper->escapeHtmlAttr($magewire->getError('vatNumber')) ?></div>
            <?php endif; ?>
        </div>
        <?php
    } ?>

</div>
