<?php

declare(strict_types=1);
/** @var Escaper $escaper */
/** @var \Buckaroo\HyvaCheckout\Magewire\Checkout\Payment\Method\Creditcards $magewire */

use Magento\Framework\Escaper;

?>
<div class="col-span-6">

    <form x-data="buckaroo.credicards($el)" x-init="register(); initCreditCardFields()" novalidate>
        <div class="flex flex-col gap-y-2 field field-reserved">
            <label id="cc-name-label" for="cc-name-wrapper">
                <?= $escaper->escapeHtml(__('Cardholder Name:')); ?>
                <span class="text-red-600">*</span>
            </label>
            <div id="cc-name-wrapper"
                 class="shadow h-12 appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
            </div>
            <div id="cc-name-error" class="text-red-600 text-sm"></div>
        </div>

        <div class="flex flex-col gap-y-2 field field-reserved">
            <label id="cc-number-label" for="cc-number-wrapper">
                <?= $escaper->escapeHtml(__('Card Number:')); ?>
                <span class="text-red-600">*</span>
            </label>
            <div id="cc-number-wrapper"
                 class="shadow h-12 appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
            </div>
            <div id="cc-number-error" class="text-red-600 text-sm"></div>
        </div>

        <div class="field field-reserved">
            <div class="flex gap-x-2 gap-y-2">
                <div class="flex flex-col w-7/12">
                    <label id="cc-expiry-label" for="cc-expiry-wrapper">
                        <?= $escaper->escapeHtml(__('Expiry Date:')); ?>
                        <span class="text-red-600">*</span>
                    </label>
                    <div id="cc-expiry-wrapper"
                         class="shadow h-12 appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
                    </div>
                    <div id="cc-expiry-error" class="text-red-600 text-sm"></div>
                </div>

                <div class="flex flex-col w-5/12">
                    <label id="cc-cvc-label" for="cc-cvc-wrapper">
                        <?= $escaper->escapeHtml(__('CVC / CVV:')); ?>
                        <span class="text-red-600">*</span>
                    </label>
                    <div id="cc-cvc-wrapper"
                         class="shadow h-12 appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
                    </div>
                    <div id="cc-cvc-error" class="text-red-600 text-sm"></div>
                </div>
            </div>
        </div>

        <div class="field">
            <span><?= $escaper->escapeHtml(__('Please make sure all fields are filled in correctly before proceeding.')); ?></span>
            <a class="text-gray-500 hover:text-gray-800 float-right ml-2" href="#" @click.prevent="resetHostedFields"><?= $escaper->escapeHtml(__('Clear')); ?></a>
        </div>

        <div x-show="oauthTokenError" class="field text-red-600 text-sm" x-text="oauthTokenError"></div>
        <div x-show="paymentError" class="field text-red-600 text-sm" x-text="paymentError"></div>
    </form>
</div>

