<?php

declare(strict_types=1);
/** @var Escaper $escaper */
/** @var \Buckaroo\HyvaCheckout\Magewire\Checkout\Payment\Method\Giftcards $magewire */

use Magento\Framework\Escaper;

if (!$magewire->isRedirect()) {
?>
    <div class="col-span-6">
        <form x-data="buckaroo.giftcards($el)" x-init="register()" novalidate>

            <div class="flex flex-col gap-y-2 field field-reserved">
                <label for="buckaroo_giftcard_issuer">
                    <?= $escaper->escapeHtml(__('Select giftcard issuer:')); ?>
                </label>
                <select
                    name="issuer"
                    id="buckaroo_giftcard_issuer"
                    x-model="card"
                    data-validate='{"required": true}'
                    class="form-select"
                >
                    <option value=""><?= $escaper->escapeHtml(__('Please select issuer')); ?></option>
                    <?php
                    foreach ($magewire->getGiftcardIssuers() as $issuer) {
                    ?>
                        <option value="<?= $escaper->escapeHtmlAttr($issuer["code"]) ?>">
                            <?= $escaper->escapeHtml($issuer["title"]) ?>
                        </option>
                    <?php
                    }
                    ?>
                </select>

            </div>

            <div class="flex flex-col gap-y-2 field field-reserved">
                <label for="buckaroo_giftcard_card_number">
                    <?= $escaper->escapeHtml(__('Card number:')); ?>
                    <span class="text-red-600">*</span>
                </label>
                <input
                    type="text"
                    x-model="cardNumber"
                    data-validate='{"required": true}'
                    @change="onChange"
                    id="buckaroo_giftcard_card_number"
                    name="buckaroo_giftcard_number"
                />
            </div>
            <div class="flex flex-col gap-y-2 field field-reserved">
                <label for="buckaroo_giftcard_pin">
                    <?= $escaper->escapeHtml(__('PIN / Security code:')); ?>
                    <span class="text-red-600">*</span>
                </label>
                <input
                    type="text"
                    x-model="pin"
                    data-validate='{"required": true}'
                    @change="onChange"
                    id="buckaroo_giftcard_pin"
                    name="buckaroo_giftcard_pin"
                />
            </div>
            <button type="button" @click="submit" class="btn btn-primary">
            <?= $escaper->escapeHtml(__('Apply Gift Card')); ?>
        </button>
        </form>
    </div>
<?php
} else {
    echo "<div></div>";
}
