<?php

declare(strict_types=1);
/** @var Escaper $escaper */
/** @var \Buckaroo\HyvaCheckout\Magewire\Checkout\Payment\Method\Giropay $magewire */

use Magento\Framework\Escaper;

$genders = $magewire->getGenderList();

?>
<div class="col-span-6">
    <div class="flex flex-col gap-y-2 field field-reserved">
        <label for="buckaroo_giropay_bic">
            <?= $escaper->escapeHtml(__('BIC Number')); ?>
            <span class="text-red">*</span>
        </label>
        <input type="text" wire:model.lazy="bic" id="buckaroo_giropay_bic" placeholder="<?= $escaper->escapeHtml(__('AAAABBCCDDD')); ?>">
        <?php if ($magewire->hasError('bic')) : ?>
            <div class="text-red"><?= $escaper->escapeHtmlAttr($magewire->getError('bic')) ?></div>
        <?php endif; ?>
    </div>
</div>