<?php

declare(strict_types=1);
/** @var Escaper $escaper */
/** @var \Buckaroo\HyvaCheckout\Magewire\Checkout\Payment\Method\In3 $magewire */

use Magento\Framework\Escaper;
?>
<div class="col-span-6">
    <div class="flex flex-col gap-y-2 field field-reserved">
        <label for="buckaroo_capayablein3_tos_fullname">
            <?= $escaper->escapeHtml(__('Billing Name:')); ?>
        </label>
        <input
            type="text"
            wire:model.lazy="fullName"
            disabled
            id="buckaroo_capayablein3_tos_fullname"
            class="bg-gray-200"
        >
    </div>

    <div class="flex flex-col gap-y-2 field field-reserved">
        <label for="buckaroo_capayablein3_dob">
            <?= $escaper->escapeHtml(__('Date of Birth:')); ?>
            <span class="text-red-600">*</span>
        </label>
        <input
            type="date"
            x-data
            value="<?= $magewire->dateOfBirth ?>"
            @blur="$wire.call('updatedDateOfBirth', $event.target.value)"
            id="buckaroo_capayablein3_dob"
        >
        <?php if ($magewire->hasError('dateOfBirth')) : ?>
            <div class="text-red-600"><?= $escaper->escapeHtmlAttr($magewire->getError('dateOfBirth')) ?></div>
        <?php endif; ?>
    </div>


    <?php if ($magewire->showPhone()) {
    ?>
        <div class="flex flex-col gap-y-2 field field-reserved">
            <label for="buckaroo_capayablein3_phone">
                <?= $escaper->escapeHtml(__('Telephone:')); ?>
                <span class="text-red-600">*</span>
            </label>
            <input type="text" wire:model.lazy="phone" id="buckaroo_capayablein3_phone">
            <?php if ($magewire->hasError('phone')) : ?>
                <div class="text-red-600"><?= $escaper->escapeHtmlAttr($magewire->getError('phone')) ?></div>
            <?php endif; ?>
        </div>
    <?php
    } ?>
</div>
