<?php

declare(strict_types=1);
/** @var Escaper $escaper */
/** @var \Buckaroo\HyvaCheckout\Magewire\Checkout\Payment\Method\Klarna $magewire */

use Magento\Framework\Escaper;

$genders = $magewire->getGenderList();

?>
<div class="col-span-6">
    <div class="flex flex-col gap-y-2">
        <label for="buckaroo_klarna_gender"><?= $escaper->escapeHtml(__('Salutation:')); ?></label>
        <select name="issuer" id="buckaroo_klarna_gender" wire:model="gender" class="form-select">
            <option value=""><?= $escaper->escapeHtml(__('-- Please Select Your Gender--')); ?></option>
            <?php
            foreach ($genders as $gender) {
            ?>
                <option value="<?= $escaper->escapeHtmlAttr($gender["code"]) ?>">
                    <?= $escaper->escapeHtml($gender["name"]) ?>
                </option>
            <?php
            }
            ?>
        </select>
    </div>

    <?php if ($magewire->showFinancialWarning()): ?>
        <div class="mt-4 p-4 bg-yellow-50 border border-yellow-200 rounded-lg">
            <div class="flex">
                <div class="ml-3">
                    <p class="text-sm text-yellow-800">
                        <?= $escaper->escapeHtml(__('Je moet minimaal 18+ zijn om deze dienst te gebruiken. Als je op tijd betaalt, voorkom je extra kosten en zorg je dat je in de toekomst nogmaals gebruik kunt maken van de diensten van Achteraf betalen via %1. Door verder te gaan, accepteer je de <a target="_blank" href="%2" class="underline">Algemene Voorwaarden</a> en bevestig je dat je de <a target="_blank" href="%3" class="underline">Privacyverklaring</a> en <a target="_blank" href="%4" class="underline">Cookieverklaring</a> hebt gelezen.', $magewire->getPaymentMethodTitle(), 'https://cdn.klarna.com/1.0/shared/content/legal/terms/EID/nl_nl/invoice', 'https://cdn.klarna.com/1.0/shared/content/legal/terms/0/nl_nl/privacy', 'https://cdn.klarna.com/1.0/shared/content/legal/terms/nl-NL/cookie_purchase'), ['a']) ?>
                    </p>
                </div>
            </div>
        </div>
    <?php endif; ?>
</div>
