<?php

declare(strict_types=1);
/** @var Escaper $escaper */
/** @var \Buckaroo\HyvaCheckout\Magewire\Checkout\Payment\Method\MrCash $magewire */

use Magento\Framework\Escaper;

?>
<div class="col-span-6">
    <?php if ($magewire->showClientSideEncryption()) {
    ?>
        <form x-data="buckaroo.mrCash($el)" x-init="register()" novalidate>
            <div class="flex flex-col gap-y-2 field field-reserved">
                <label for="buckaroo_mrcash_card_holder">
                    <?= $escaper->escapeHtml(__('Name on card:')); ?>
                    <span class="text-red-600">*</span>
                </label>
                <input
                    type="text"
                    x-model="cardHolder"
                    data-validate='{"bk-validateCardHolderName": true}'
                    @change="onChange"
                    id="buckaroo_mrcash_card_holder"
                    name="buckaroo_mrcash_card_holder"
                    placeholder="<?= $escaper->escapeHtml(__('John Doe')); ?>"
                />
            </div>

            <div class="field field-reserved">
                <div class="flex gap-x-2">
                    <div class="flex flex-col gap-y-2  w-8/12">
                        <label for="buckaroo_mrcash_card_number">
                            <?= $escaper->escapeHtml(__('Card number:')); ?>
                            <span class="text-red-600">*</span>
                        </label>
                        <input
                            type="text"
                            x-model="cardNumber"
                            data-validate='{"bk-validateCardNumber": true}'
                            @change="onChange"
                            id="buckaroo_mrcash_card_number"
                            name="buckaroo_mrcash_card_number"
                            placeholder="<?= $escaper->escapeHtml(__('0000 0000 0000 0000')); ?>"
                        />
                    </div>

                    <div class="flex flex-col gap-y-2  w-4/12">
                        <label for="buckaroo_mrcash_card_expiration">
                            <?= $escaper->escapeHtml(__('Expiration:')); ?>
                            <span class="text-red-600">*</span>
                        </label>
                        <input
                            type="text"
                            maxlength="5"
                            x-model="cardExpiration"
                            data-validate='{"bk-ValidateYear": true, "bk-ValidateMonth": true}'
                            @change="onChange"
                            id="buckaroo_mrcash_card_expiration"
                            name="buckaroo_mrcash_card_expiration"
                            placeholder="<?= $escaper->escapeHtml(__('MM/YY')); ?>"
                        />
                    </div>
                </div>
            </div>
        </form>
    <?php
    } ?>
</div>
