<?php

declare(strict_types=1);
/** @var Escaper $escaper */
/** @var \Buckaroo\HyvaCheckout\Magewire\Checkout\Payment\Method\Tinka $magewire */

use Magento\Framework\Escaper;
?>
<div class="col-span-6">
    <div class="flex flex-col gap-y-2 field field-reserved">
        <label for="buckaroo_afterpay20_tos_fullname">
            <?= $escaper->escapeHtml(__('Billing Name:')); ?>
        </label>
        <input type="text" wire:model.lazy="fullName" disabled id="buckaroo_afterpay20_tos_fullname" class="bg-gray-200">
    </div>

    <?php if ($magewire->showBirth()) {
    ?>
        <div class="flex flex-col gap-y-2 field field-reserved">
            <label for="buckaroo_afterpay20_dob">
                <?= $escaper->escapeHtml(__('Date of Birth:')); ?>
                <span class="text-red">*</span>
            </label>
            <input type="date" x-data value="<?= $magewire->dateOfBirth ?>" @blur="$wire.call('updatedDateOfBirth', $event.target.value); console.log($event.target.value)" id="buckaroo_afterpay20_dob">
            <?php if ($magewire->hasError('dateOfBirth')) : ?>
                <div class="text-red"><?= $escaper->escapeHtmlAttr($magewire->getError('dateOfBirth')) ?></div>
            <?php endif; ?>
        </div>
    <?php
    } ?>

    <?php if ($magewire->showPhone()) {
    ?>
        <div class="flex flex-col gap-y-2 field field-reserved">
            <label for="buckaroo_afterpay20_phone">
                <?= $escaper->escapeHtml(__('Telephone:')); ?>
                <span class="text-red">*</span>
            </label>
            <input type="text" wire:model.lazy="phone" id="buckaroo_afterpay20_phone">
            <?php if ($magewire->hasError('phone')) : ?>
                <div class="text-red"><?= $escaper->escapeHtmlAttr($magewire->getError('phone')) ?></div>
            <?php endif; ?>
        </div>
    <?php
    } ?>


</div>