<?php

declare(strict_types=1);
/** @var Escaper $escaper */
/** @var \Buckaroo\HyvaCheckout\Magewire\Checkout\Payment\Method\Voucher $magewire */

use Magento\Framework\Escaper;

?>
<div class="col-span-6">

    <form x-data="buckarooVoucher" data-ajax-url="<?= $escaper->escapeUrl($magewire->getAjaxUrl()); ?>" novalidate>
        <div class="flex flex-col gap-y-2 field field-reserved">
            <label for="buckaroo_voucher_code">
                <?= $escaper->escapeHtml(__('Voucher code:')); ?>
                <span class="text-red-600">*</span>
            </label>
            <input
                type="text"
                x-bind:value="code"
                @input="updateCode"
                data-validate='{"required": true}'
                id="buckaroo_voucher_code"
                name="buckaroo_voucher_code"
                placeholder="<?= $escaper->escapeHtml(__('1A2B-3C4D-6E7F-8G9H-1I2J')); ?>"
            />
        </div>
        <button type="button" @click="submit" class="btn btn-primary">
            <?= $escaper->escapeHtml(__('Apply Voucher')); ?>
        </button>
    </form>
</div>
