<?php

declare(strict_types=1);


/** @var Template $block */
/** @var FormatterViewModel $formatterViewModel */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Checkout\ViewModel\Checkout\Formatter as FormatterViewModel;
use Hyva\Theme\Model\ViewModelRegistry;

$formatterViewModel = $viewModels->require(FormatterViewModel::class);
$total = $block->getSegment();

if ($total['value'] != 0) {

?>
    <div class="flex gap-4 justify-between md:gap-0">
        <span class="label font-bold">
            <?= $block->escapeHtml($total['title']) ?>
        </span>
        <span class="value"><?= /* @noEscape */ $formatterViewModel->currency($total['value'] ?? 0) ?></span>
    </div>
<?php
}
