<?php

declare(strict_types=1);


/** @var Template $block */
/** @var FormatterViewModel $formatterViewModel */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Checkout\ViewModel\Checkout\Formatter as FormatterViewModel;
use Hyva\Theme\Model\ViewModelRegistry;

$formatterViewModel = $viewModels->require(FormatterViewModel::class);
$segment = $block->getSegment();
if ($segment['value'] != 0) {
?>
    <div class="flex gap-4 justify-between md:gap-0">
        <span class="label">
            <?= $block->escapeHtml($block->getTitle()) ?>
        </span>
        <span class="value">
            <?= /* @noEscape */ $formatterViewModel->currency($segment['value'] ?? 0) ?>
        </span>
    </div>
<?php
}
